name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    name: "Node ${{ matrix.node-version }}"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: yarn
    - run: yarn lint && yarn test

  release-it-compat:
    name: "release-it@${{ matrix.release-it-version }}"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        release-it-version: ["15.2.0", "15.5.0"]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install dependencies
      run: yarn
    - run: yarn add -D release-it@${{ matrix.release-it-version }}
    - run: yarn test
